---
- name: Install iSCSI and Multipath tools on Kubernetes Nodes
  hosts: all
  become: true
  tasks:
    - name: Install open-iscsi and multipath-tools
      apt:
        name:
          - open-iscsi
          - multipath-tools
        state: present
        update_cache: yes

    - name: Enable and start iscsid service
      systemd:
        name: iscsid
        enabled: yes
        state: started

    - name: Enable and start multipathd service
      systemd:
        name: multipathd
        enabled: yes
        state: started

    - name: Ensure multipath.conf exists with defaults
      copy:
        dest: /etc/multipath.conf
        content: |
          defaults {}
        mode: "0644"

    - name: Restart multipathd to load new config
      systemd:
        name: multipathd
        state: restarted
