---
# - name: Configure HAProxy on load balancer nodes
#   hosts: load_balancer
#   roles:
#     - haproxy
# In case of external load balancer

- name: Configure k3s masters
  hosts: server
  roles:
    - k3s

# - name: Add workers to the k3s cluster
#   hosts: agent
#   roles:
#     - k3s
