- name: Test become_user in Ansible
  hosts: server
  become: yes # Enable privilege escalation (e.g., sudo)
  tasks:
    - name: Show current user
      command: whoami
      register: current_user

    - name: Display the user
      debug:
        var: current_user.stdout
