---
- include_tasks: install_docker.yaml

- name: Install kubectl with binary
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

- name: Download kubectl SHA256 checksum
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"

- name: Validate kubectl binary checksum
  ansible.builtin.shell: |
    echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check

- name: Install kubectl binary
  ansible.builtin.shell: |
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    kubectl version --client

- name: Disable swap temporarily
  ansible.builtin.shell: |
    sudo swapoff -a

- name: Install k8s v1.33 and dependencies
  ansible.builtin.shell: |
    sudo apt-get update && \
    sudo apt-get install -y apt-transport-https ca-certificates curl gpg && \
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg && \
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list && \
    sudo apt-get update && \
    sudo apt-get install -y kubelet kubeadm kubectl && \
    sudo apt-mark hold kubelet kubeadm kubectl

- include_tasks: init_k8s_main_master.yaml
  when: inventory_hostname == groups['server'][0]