---
- name: Disable swap temporarily
  ansible.builtin.shell: sudo swapoff -a
  when: inventory_hostname in groups['agent']

- name: Ensure swap is disabled permanently
  ansible.builtin.shell: sudo sed -i '/swap/d' /etc/fstab
  when: inventory_hostname in groups['agent']

- name: Install kubeadm, kubelet, and kubectl
  ansible.builtin.shell: |
    sudo apt-get update && \
    sudo apt-get install -y apt-transport-https ca-certificates curl gpg && \
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg && \
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list && \
    sudo apt-get update && \
    sudo apt-get install -y kubelet kubeadm kubectl && \
    sudo apt-mark hold kubelet kubeadm kubectl
  when: inventory_hostname in groups['agent']

- name: Join worker node to the cluster
  ansible.builtin.shell: |
    sudo kubeadm join --token {{ k8s_token.stdout }} {{ hostvars[groups['server'][0]].ansible_host }}:6443 --discovery-token-ca-cert-hash sha256:{{ ca_cert_hash.stdout }}
  when: inventory_hostname in groups['agent']
