- name: Install linux-modules-extra for current kernel (for br_netfilter)
  apt:
    name: "linux-modules-extra-{{ ansible_kernel }}"
    state: present

- name: Ensure br_netfilter module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: Persist br_netfilter in /etc/modules-load.d
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: "br_netfilter"
    mode: '0644'


- name: Install kubeadm dependencies
  apt:
    name:
      - socat
      - conntrack
      - iptables
      - ebtables
      - ethtool
      - bridge-utils
      - apt-transport-https
    state: present

- name: Enable bridge-nf-call-iptables (and related sysctls)
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Enable net.bridge.bridge-nf-call-ip6tables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Get OS codename
  command: lsb_release -cs
  register: os_codename
  changed_when: false

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required dependencies
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg
      - software-properties-common
    state: present

- name: Download Kubernetes GPG key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    mode: '0644'
  when: os_codename.stdout != "noble"

- name: Add Kubernetes APT repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
    update_cache: yes
  when: os_codename.stdout != "noble"