- name: Check if containerd is already installed
  command: which containerd
  register: containerd_check
  ignore_errors: true

- name: Install containerd if not installed
  apt:
    name: containerd
    state: present
  when: containerd_check.rc != 0

- name: Generate default containerd config if not already present
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Set pause image to version 3.9 in containerd config
  become: true
  replace:
    path: /etc/containerd/config.toml
    regexp: 'sandbox_image = ".*"'
    replace: 'sandbox_image = "registry.k8s.io/pause:3.9"'

- name: Restart containerd after config change
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Ensure containerd is running and enabled
  systemd:
    name: containerd
    state: started
    enabled: yes