- name: Ensure kubelet systemd override directory exists
  become: true
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    mode: '0755'

- name: Configure kubelet to use containerd and systemd cgroup driver
  become: true
  copy:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    content: |
      [Service]
      Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --cgroup-driver=systemd"
    mode: '0644'

- name: Reload and restart kubelet to apply config
  become: true
  shell: |
    systemctl daemon-reexec
    systemctl daemon-reload
    systemctl restart kubelet

- name: Get OS codename
  ansible.builtin.command: lsb_release -cs
  register: os_codename
  changed_when: false

- name: Debug codename
  debug:
    var: os_codename.stdout

- name: Install Kubernetes tools via apt (Ubuntu <= 22.04)
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  when: os_codename.stdout != 'noble'

- name: Hold kubelet, kubeadm, kubectl (Ubuntu <= 22.04)
  apt:
    name: "{{ item }}"
    state: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  when: os_codename.stdout != 'noble'

- name: Download kubeadm binary (Ubuntu 24.04)
  get_url:
    url: https://dl.k8s.io/release/v1.29.1/bin/linux/amd64/kubeadm
    dest: /usr/local/bin/kubeadm
    mode: '0755'
  when: os_codename.stdout == 'noble'

- name: Download kubectl binary (Ubuntu 24.04)
  get_url:
    url: https://dl.k8s.io/release/v1.29.1/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
  when: os_codename.stdout == 'noble'

- name: Download kubelet binary (Ubuntu 24.04)
  get_url:
    url: https://dl.k8s.io/release/v1.29.1/bin/linux/amd64/kubelet
    dest: /usr/local/bin/kubelet
    mode: '0755'
  when: os_codename.stdout == 'noble'

- name: Create kubelet systemd service (Ubuntu 24.04)
  copy:
    dest: /etc/systemd/system/kubelet.service
    content: |
      [Unit]
      Description=kubelet: The Kubernetes Node Agent
      Documentation=https://kubernetes.io/docs/
      After=network-online.target

      [Service]
      ExecStart=/usr/local/bin/kubelet
      Restart=always
      StartLimitInterval=0
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
  when: os_codename.stdout == 'noble'

- name: Enable kubelet service (Ubuntu 24.04)
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes
  when: os_codename.stdout == 'noble'