- name: Disable swap
  shell: swapoff -a

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^.* swap .*$'
    replace: ''

- name: Enable bridge netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Enable sysctl bridge
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Enable IP forward
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes