  # load_balancer:
  #   hosts:
  #     lb1:
  #       ansible_host: x.x.x.x
  #       ansible_ssh_private_key_file: /path/to/key

  server:
    hosts:
      apollo:
        ansible_host: x.x.x.x
        ansible_ssh_private_key_file: /path/to/key
      boreas:
        ansible_host: x.x.x.x
        ansible_ssh_private_key_file: /path/to/key
      ares:
        ansible_host: x.x.x.x
        ansible_ssh_private_key_file: /path/to/key

  agent:
    hosts:
      chaos:
        ansible_host: x.x.x.x
        ansible_ssh_private_key_file: /path/to/key
      crios:
        ansible_host: x.x.x.x
        ansible_ssh_private_key_file: /path/to/key
      hades:
        ansible_host: x.x.x.x
        ansible_ssh_private_key_file: /path/to/key
  cluster:
    children:
      server:
      agent:
      # load_balancer:
