  # load_balancer:
  #   hosts:
  #     lb1:
  #       ansible_host: 192.168.24.81
  #       ansible_ssh_private_key_file: ~/Downloads/id_rsa

  server:
    hosts:
      apollo:
        ansible_host: 192.168.24.100
        ansible_ssh_private_key_file: ~/Downloads/id_rsa
      boreas:
        ansible_host: 192.168.24.101
        ansible_ssh_private_key_file: ~/Downloads/id_rsa
      ares:
        ansible_host: 192.168.24.102
        ansible_ssh_private_key_file: ~/Downloads/id_rsa

  agent:
    hosts:
      chaos:
        ansible_host: 192.168.24.80
        ansible_ssh_private_key_file: ~/Downloads/id_rsa
      crios:
        ansible_host: 192.168.24.82
        ansible_ssh_private_key_file: ~/Downloads/id_rsa
      hades:
        ansible_host:
        ansible_ssh_private_key_file:
  cluster:
    children:
      server:
      agent:
      # load_balancer:
