  # load_balancer:
  #   hosts:
  #     lb1:
  #       ansible_host: x.x.x.x
        # ansible_ssh_private_key_file: /path/to/key

  server:
    hosts:
      apollo-18:
        ansible_host: x.x.x.x
        ansible_user: username
        ansible_ssh_private_key_file: /path/to/key
        become: true
        become_user: root
      boreas:
        ansible_host: x.x.x.x
        ansible_user: username
        ansible_ssh_private_key_file: /path/to/key
        become: true
        become_user: root
      ares:
        ansible_host: x.x.x.x
        ansible_user: username
        ansible_ssh_private_key_file: /path/to/key
        become: true
        become_user: root

  # agent:
  #   hosts:
  #     chaos:
  #       ansible_host: x.x.x.x
  #       ansible_user: username
  #       ansible_ssh_private_key_file: /path/to/key
  #       become: true
  #       become_user: root
      # crios:
      #   ansible_host: <x.x.x.x>
      #   ansible_user: <user>
      #   ansible_password: <password>
      #   # ansible_ssh_private_key_file: path/to/your/ssh/key
      #   become: true
      #   become_user: <user>
      #   become_password: <password>
      # hades:
      #   ansible_host: <x.x.x.x>
      #   ansible_user: <user>
      #   ansible_password: <password>
      #   # ansible_ssh_private_key_file: path/to/your/ssh/key
      #   become: true
      #   become_user: <user>
      #   become_password: <password>
  cluster:
    children:
      server:
      agent:
      # load_balancer:
