  # load_balancer:
  #   hosts:
  #     lb1:
  #       ansible_host: x.x.x.x
  #       ansible_ssh_private_key_file: /path/to/key

  server:
    hosts:
      apollo:
        ansible_host: 192.168.24.46
        ansible_user: systemadmin
        ansible_become: true
        ansible_ssh_private_key_file: ~/ssh/prince_vm
        become: true
        become_user: systemadmin
        become_password: qwer1234!@#$
  #     boreas:
  #       ansible_host: <host-machine-ip>
  #       ansible_user: <host-username>
  #       ansible_ssh_private_key_file: path/to/your/ssh/key
  #       become: true
  #       become_user: <host-username>
  #       become_password: <host-password>
  #     ares:
  #       ansible_host: <host-machine-ip>
  #       ansible_user: <host-username>
  #       ansible_ssh_private_key_file: path/to/your/ssh/key
  #       become: true
  #       become_user: <host-username>
  #       become_password: <host-password>

  agent:
    hosts:
      chaos:
        ansible_host: 192.168.24.47
        ansible_user: systemadmin
        ansible_ssh_private_key_file: ~/ssh/prince_vm
        become: true
        become_user: systemadmin
        become_password: qwer1234!@#$
  #     crios:
  #       ansible_host: <host-machine-ip>
  #       ansible_user: <host-username>
  #       ansible_ssh_private_key_file: path/to/your/ssh/key
  #       become: true
  #       become_user: <host-username>
  #       become_password: <host-password>
  #     hades:
  #       ansible_host: <host-machine-ip>
  #       ansible_user: <host-username>
  #       ansible_ssh_private_key_file: path/to/your/ssh/key
  #       become: true
  #       become_user: <host-username>
  #       become_password: <host-password>
  cluster:
    children:
      server:
      agent:
      # load_balancer:
