---
- include_tasks: install_k3s_master.yaml
  when: inventory_hostname == groups['server'][0]

- include_tasks: install_k3s_secondary_master.yaml
  when: inventory_hostname != groups['server'][0] and inventory_hostname in groups['server'][1]

- include_tasks: install_k3s_third_master.yaml
  when: inventory_hostname != groups['server'][0] and inventory_hostname in groups['server'][2]

# - include_tasks: install_k3s_worker.yaml
#   when: inventory_hostname in groups['agent']
