---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages to prevent unintended upgrades
  shell: apt-mark hold kubelet kubeadm kubectl