- name: Install Kubernetes packages if not installed
  include_tasks: 01-install_kubernetes.yaml
  when: "'kubelet' not in ansible_facts.packages"

- name: Install base dependencies (containerd config, etc.) if containerd config missing
  include_tasks: 02-install_deps.yaml
  when: containerd_config_file.stat.exists == false

- name: Enable and start essential services
  include_tasks: 03-start_services.yaml