---
- name: Unhold Kubernetes packages (if held)
  shell: apt-mark unhold kubelet kubeadm kubectl || true

- name: Reset kubeadm if exists
  shell: kubeadm reset -f || true
  ignore_errors: true

- name: Check if containerd service file exists
  stat:
    path: /lib/systemd/system/containerd.service
  register: containerd_service

- name: Stop kubelet and containerd if running
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - kubelet
    - containerd
  when: item != 'containerd' or containerd_service.stat.exists
  ignore_errors: true