---
- name: Enable IP forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes
  become: true

# Set systemd load module br_netfilter everytime after boot
- name: Allow iptables to see bridged traffic
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
  become: true

# Force start module br_netfilter
- name: Ensure br_netfilter is loaded
  ansible.builtin.modprobe:
    name: br_netfilter
  become: true

- name: Set required sysctl params
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: true

- name: Apply sysctl params
  ansible.builtin.command: sysctl --system
  become: true