---
- name: Comment out swap in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+)'
    replace: '# \1'
  become: true

- name: Disable all active swap
  ansible.builtin.shell: swapoff -a
  args:
    warn: false
  when: ansible_swaptotal_mb > 0
  become: true